---
#
- name: prepare installation response file
  template:
    src: install-wls-12c.rsp.j2
    dest: "{{ oracle_weblogic_response_file }}"
  when: not oracle_weblogic_quick_installation
  
- name: download file from a file path
  get_url:
    url: "https://s3.eu-central-1.amazonaws.com/dog-oracledb-files/fmw_12.2.1.3.0_infrastructure.jar"
    dest: fmw_12.2.1.3.0_infrastructure.jar

- set_fact:
    oracle_weblogic_install_command: "java -jar fmw_12.2.1.3.0_infrastructure.jar ORACLE_HOME={{ oracle_weblogic_oracle_home }} >> /tmp/weblogic-installation.log"
  when: oracle_weblogic_quick_installation

- set_fact:
    oracle_weblogic_install_command: "java -jar fmw_12.2.1.3.0_infrastructure.jar -silent -responseFile {{ oracle_weblogic_response_file }} >> /tmp/weblogic-installation.log"
  when: not oracle_weblogic_quick_installation

- name: install weblogic
  shell: "{{ oracle_weblogic_install_command }}"
  args:
    creates: "{{ oracle_weblogic_oracle_home }}/oraInst.loc"
